apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: voting-app
spec:
  volumeName: pv-1
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
