apiVersion: v1
kind: Pod
metadata: 
  name: worker
  namespace: voting-app
  labels:
    name: worker
    app: voting-app
spec: 
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker

